Repository matplotlib/mpl-third-party, pull requests merged in 2021-05, with the labels that each got.

#31 recategorized speciality and misc
  packages/DnaFeaturesViewer.yml
  packages/adjustText.yml
  packages/astropy.yml
  packages/blume.yml
  packages/brokenaxes.yml
  packages/figpager.yml
  packages/grid-strategy.yml
  packages/matplotlib-scalebar.yml
  packages/matplotlib-venn.yml
  packages/mpl-probscale.yml
  packages/mpl-template.yml
  packages/mplfinance.yml
  packages/mplstereonet.yml
  packages/plotnine.yml
  packages/pyupset.yml
  packages/seaborn.yml
  packages/sphinx-gallery.yml
  packages/windrose.yml
  packages/yellowbrick.yml
  python/build.py
Labels: needs discussion

#46 changed mplsoccer section
  packages/mplsoccer.yml
Labels: maintenance

#58 Site is optional
  README.md
Labels: documentation

#62 Remove toctree from template.
  python/template.rst
Labels: bug

#63 Add section heading links.
  python/template.rst
Labels: enhancement

#64 Use pathlib everywhere.
  python/build.py
  python/build_cache.py
  python/conda_downloads.py
Labels: maintenance

#66 Cleanup CSS
  docs/source/_static/custom.css
  docs/source/_static/favicon.ico
  docs/source/_static/logo.png
  docs/source/conf.py
  python/template.rst
Labels: maintenance
