Repository matplotlib/mpl-third-party, pull requests merged in 2021-04, with the labels that each got.

#5 Pkg add a few more
  packages/windrose.yml
  packages/yellowbrick.yml
Labels: package

#6 MNT: Some re-organization
  README.md
  docs/Makefile
  docs/source/conf.py
  docs/source/index.rst
  docs/source/intro.rst
  python/README.md
  python/build.py
  python/build_cache.py
  python/conda_downloads.py
  python/template.rst
Labels: maintenance

#25 Fix PyPI capitalization.
  python/build.py
Labels: formatting

#34 DOC: readme typo, expanded instructructions
  README.md
Labels: documentation
